name: Data Archive

on:
  push:
  workflow_dispatch:
  schedule:
  - cron: '0 */1 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download recently changed data.
      run: |
        curl --compressed https://mcbroken2.nyc3.digitaloceanspaces.com/markers.json \
          | jq '[ .features[] | select(.properties.last_checked | match("[0-9]+").string | tonumber < 180) ]' > mcbroken.json
    - name: Commit data
      run: |
        git config user.name "Rashiq"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        git commit -m "Archive from $(date -u)" || exit 0
        git push
